services:
##MSPEDIDOS##
  #BANCO
  db-pedidos:
    image: postgres:latest
    container_name: db-pedidos
    volumes:
      - postgres_data_pedidos:/var/lib/postgresql/data
    # ports: #caso precise acessar o banco externamente
    #   - "5432:5432"
    environment:
      POSTGRES_DB: pedidos
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always
    networks:
      - sgpism_network
    
  #APLICAÇAO
  mspedidos:
    container_name: mspedidos
    build:
      context: .
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-pedidos/pedidos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db-pedidos
    # restart: none
    networks:
      - sgpism_network   

##CONFIG NETWORKS
networks:
  sgpism_network:
    driver: bridge

volumes:
  postgres_data_pedidos: